name: "Russound"
description: "An add-on to integrate russound caa-66 into home assistant"
version: "1.0.2"
slug: "russound"
init: false
startup: "services"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /dev/ttyUSB0
ports:
  "3333/tcp": 3333
map:
  - addons
