name: "Russound"
description: "An add-on to integrate russound caa-66 into home assistant"
version: "1.0.1"
slug: "russound"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
#devices:
#  - /dev/ttyUSB0:/dev/ttyUSB0:rwm
